name: mental-health-risk-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - xgboost
  - shap
  - lime
  - matplotlib
  - seaborn
  - joblib
  - pyyaml
  - pytest
